server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-REGISTRY
              uri: lb://USER-REGISTRY
              predicates:
                - Path=/ur/**
              filters:
                - AuthenticationFilter

            - id: PSO-SERVICES
              uri: lb://PSO-SERVICES
              predicates:
                - Path=/ps/**
              filters:
                - AuthenticationFilter

  application:
    name: PSO-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
