server:
  port: 8081
  servlet:
    context-path: /ps/

spring:
  application:
    name: PSO-SERVICES
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: prashant
    url: jdbc:mysql://localhost:3306/pso_db
    username: pso
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
