server:
  port: 8081
  servlet:
    context-path: /ps/

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    bootstrap-servers: kafka:9092
  application:
    name: PSO-SERVICES
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: prashant
    url: jdbc:mysql://db:3306/pso_db?useSSL=false&allowPublicKeyRetrieval=true
    username: pso
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
