server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-REGISTRY
              order: 1
              uri: lb://USER-REGISTRY
              predicates:
                - Path=/ur/**
              filters:
                - AuthenticationFilter
                - RemoveResponseHeader=WWW-Authenticate

            - id: PSO-SERVICES
              order: 2
              uri: lb://PSO-SERVICES
              predicates:
                - Path=/ps/**
              filters:
                - AuthenticationFilter
                - RemoveResponseHeader=WWW-Authenticate

            - id: ViewService
              uri: lb://ViewService
              order: 1000
              predicates:
                - Path=/**

  application:
    name: PSO-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
