FROM ubuntu:noble

# Install Java
RUN apt-get update && \
    apt-get install -y openjdk-21-jdk && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /kafka

# Copy Kafka files
COPY . .

# Expose Zookeeper client port
EXPOSE 2181

# Start Zookeeper
CMD ["./bin/zookeeper-server-start.sh", "./config/zookeeper.properties"]