FROM ubuntu:noble

# Install Java
RUN apt-get update && \
    apt-get install -y openjdk-21-jdk && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /kafka

# Copy Kafka files
COPY . .

# Expose Kafka port
EXPOSE 9092

# Start Kafka
CMD ["./bin/kafka-server-start.sh", "./config/server.properties"]